services:
  soen363-project2-neo4j:
    image: "neo4j:enterprise"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
    # portal
      - "7474:7474"
    # db
      - "7687:7687"
    volumes:
      - "../data/db/csv/:/var/lib/neo4j/import"